export const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES'
export const REMOVE_MOVIE_FROM_FAVORITES = 'REMOVE_MOVIE_FROM_FAVORITES'
export const GET_FAVORITE_MOVIES = 'GET_FAVORITE_MOVIES'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const CREATE_COMMENT = 'CREATE_COMMENT'
export const GET_COMMENTS = 'GET_COMMENTS'


export const UPDATE_RATING = 'UPDATE_RATING'
export const CREATE_RATING = 'CREATE_RATING'
export const GET_RATINGS = 'GET_RATINGS'


export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

export const SET_USER = 'SET_USER'
export const GET_USER = 'GET_USER'