export const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES'
export const REMOVE_MOVIE_FROM_FAVORITES = 'REMOVE_MOVIE_FROM_FAVORITES'

export const UPDATE_COMMENT = 'UPDATE_COMMENT'

export const UPDATE_RATING = 'UPDATE_RATING'

export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

export const SET_USER = 'SET_USER'